<?php

/**
 * @file
 * Contains invite.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function invite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the invite module.
    case 'help.page.invite':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Invite module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function invite_theme() {
  $theme = [];
  $theme['invite'] = [
    'render element' => 'elements',
    'file' => 'invite.page.inc',
    'template' => 'invite',
  ];
  $theme['invite_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'invite.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function invite_theme_suggestions_invite(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#invite'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'invite__' . $sanitized_view_mode;
  $suggestions[] = 'invite__' . $entity->bundle();
  $suggestions[] = 'invite__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'invite__' . $entity->id();
  $suggestions[] = 'invite__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
